# Generated by Django 6.0.3 on 2026-03-30 13:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_heading",
                    models.CharField(default="Hi, I'm Viktorija", max_length=255),
                ),
                ("hero_subheading", models.TextField(blank=True)),
                (
                    "story",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 0),
                            ("paragraph", 1),
                            ("image", 2),
                            ("image_text_block", 4),
                            ("quote", 5),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title"},
                            ),
                            1: ("wagtail.blocks.RichTextBlock", (), {}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Image Left"),
                                        ("right", "Image Right"),
                                    ]
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 2), ("image_position", 3), ("text", 1)]],
                                {},
                            ),
                            5: ("wagtail.blocks.BlockQuoteBlock", (), {}),
                        },
                    ),
                ),
                (
                    "credentials_heading",
                    models.CharField(default="Credentials & Training", max_length=255),
                ),
                (
                    "credentials",
                    wagtail.fields.StreamField(
                        [("credential", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            2: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("organization", 1),
                                        ("year", 1),
                                        ("logo", 2),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "philosophy_heading",
                    models.CharField(default="My Approach", max_length=255),
                ),
                ("philosophy_text", wagtail.fields.RichTextField(blank=True)),
                (
                    "personal_heading",
                    models.CharField(default="Beyond the Bio", max_length=255),
                ),
                (
                    "personal_facts",
                    wagtail.fields.StreamField(
                        [("fact", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 10, "required": False},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {}),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("emoji", 0), ("text", 1)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "cta_heading",
                    models.CharField(
                        default="Ready to Start Your Journey?", max_length=255
                    ),
                ),
                ("cta_text", models.TextField(blank=True)),
                (
                    "cta_button_text",
                    models.CharField(default="Let's Connect", max_length=100),
                ),
                (
                    "cta_button_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "About Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
