# Generated by Django 6.0.3 on 2026-04-03 05:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_heading",
                    models.CharField(
                        default="Book Your Free Discovery Call", max_length=255
                    ),
                ),
                (
                    "intro_text",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Main description below the hero"
                    ),
                ),
                (
                    "zoom_note",
                    models.CharField(
                        blank=True,
                        default="Calls are held on Zoom so we can meet from anywhere. Can't see a time that works? Email me and we'll find one that does.",
                        max_length=500,
                    ),
                ),
                (
                    "step_1",
                    models.CharField(
                        default="Book a free 45-min virtual discovery call",
                        max_length=255,
                    ),
                ),
                (
                    "step_2",
                    models.CharField(
                        default="Meet Viktorija, talk through your goals and see if it's a good fit",
                        max_length=255,
                    ),
                ),
                (
                    "step_3",
                    models.CharField(
                        default="Schedule your first full session with a package that fits your needs",
                        max_length=255,
                    ),
                ),
                (
                    "calendly_embed_url",
                    models.URLField(
                        blank=True,
                        help_text="Calendly URL for inline embed (e.g. https://calendly.com/viktorija/discovery-call)",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
