# Generated by Django 6.0.3 on 2026-03-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesettings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="calendly_url",
            field=models.URLField(
                blank=True,
                help_text="Calendly booking link (e.g. https://calendly.com/viktorija/discovery-call)",
            ),
        ),
    ]
