# Generated by Django 6.0.3 on 2026-03-30 13:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("hero_title", models.CharField(max_length=255)),
                ("hero_subtitle", models.CharField(blank=True, max_length=500)),
                (
                    "hero_cta_text",
                    models.CharField(default="Work With Me", max_length=100),
                ),
                ("about_heading", models.CharField(blank=True, max_length=255)),
                ("about_text", wagtail.fields.RichTextField(blank=True)),
                (
                    "services_heading",
                    models.CharField(default="How I Can Help", max_length=255),
                ),
                ("services_subheading", models.TextField(blank=True)),
                (
                    "services_items",
                    wagtail.fields.StreamField(
                        [("service", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Emoji or icon name", "required": False},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {}),
                            2: ("wagtail.blocks.TextBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("icon", 0), ("title", 1), ("description", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "testimonials_heading",
                    models.CharField(default="What Clients Say", max_length=255),
                ),
                (
                    "featured_testimonials",
                    wagtail.fields.StreamField(
                        [("testimonial", 4)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.TextBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {}),
                            2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            3: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("quote", 0),
                                        ("author_name", 1),
                                        ("author_title", 2),
                                        ("author_image", 3),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "newsletter_heading",
                    models.CharField(default="Join My Community", max_length=255),
                ),
                ("newsletter_text", models.TextField(blank=True)),
                ("cta_heading", models.CharField(blank=True, max_length=255)),
                ("cta_text", models.TextField(blank=True)),
                (
                    "cta_button_text",
                    models.CharField(default="Let's Connect", max_length=100),
                ),
                (
                    "about_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "cta_button_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_cta_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
