# Generated by Django 6.0.3 on 2026-04-03 05:17

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage2",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_heading",
                    models.CharField(
                        default="Your Journey Starts Here", max_length=255
                    ),
                ),
                ("hero_text", models.TextField(blank=True)),
                (
                    "hero_cta_text",
                    models.CharField(default="Book a Discovery Call", max_length=100),
                ),
                (
                    "services_heading",
                    models.CharField(default="How I Can Help", max_length=255),
                ),
                (
                    "services",
                    wagtail.fields.StreamField(
                        [("service", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {}),
                            2: ("wagtail.blocks.TextBlock", (), {}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Learn More"},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 0),
                                        ("title", 1),
                                        ("description", 2),
                                        ("link_text", 3),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                ("vision_text", wagtail.fields.RichTextField(blank=True)),
                (
                    "about_heading",
                    models.CharField(default="Meet Viktorija", max_length=255),
                ),
                ("about_text", wagtail.fields.RichTextField(blank=True)),
                (
                    "about_cta_text",
                    models.CharField(default="Learn More", max_length=100),
                ),
                (
                    "testimonials",
                    wagtail.fields.StreamField(
                        [("testimonial", 3)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.TextBlock", (), {}),
                            1: ("wagtail.blocks.CharBlock", (), {}),
                            2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("quote", 0),
                                        ("author_name", 1),
                                        ("author_title", 2),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                ("cta_heading", models.CharField(blank=True, max_length=255)),
                ("cta_text", models.TextField(blank=True)),
                (
                    "cta_button_text",
                    models.CharField(default="Book a Discovery Call", max_length=100),
                ),
                (
                    "about_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page 2",
            },
            bases=("wagtailcore.page",),
        ),
    ]
